/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dictionary.h"
#include <stdio.h>
#include <string.h>

CLIENT* createClient(char* host){
	CLIENT *clnt;
	clnt = clnt_create (host, DICTIONARY, DICTIONARY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		printf("Invalid host name [%s]", host);
		exit (1);
	}
	return clnt;
}

void dict_1(CLIENT* clnt, char op)
{
	char word[250];	
	printf("Word :");
	scanf("%s", word);

	switch(op){
		case 'I' : {
				char meaning[1000];

				printf("Meaning :");
				scanf(" %[^\n]", meaning);				

				WM* wwm;
				wwm = (WM*) malloc(sizeof(WM));
				wwm->word = (char*) malloc(sizeof(char) * strlen(word));
				strcpy(wwm->word, word);
				wwm->meaning = (char*) malloc(sizeof(char) * strlen(meaning));
				strcpy(wwm->meaning, meaning);

				char** output = newword_1(wwm, clnt);
				if (output == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
				
				break;
			}
		case 'S' : {
				char** output = searchword_1((char* []){word}, clnt);
				if (output == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
				printf("%s", *output);				
				break;
			}
		case 'D': {
				char** output = deleteword_1( (char*[]) {word}, clnt);
				if (output == (char **) NULL) {
					clnt_perror (clnt, "call failed");
				}
				if(strcmp(*output,"") == 0){
					printf("Not found [%s] to delete", word);	
				}
				break;
			}
		default: {
			printf("Unknown Operation\n");
			break;
		}
	};
	
}


int main (int argc, char *argv[])
{
	
	char host[100];
	char inputOption;
	char inputWord[250];
	char inputMeaning[1000];

	printf("Hostname :");
	scanf("%100[^\n]", host);
	
	CLIENT* clnt = createClient(host);

	while(1) {
		printf("\nI for Insert, S for Search, D for Delete :");
		scanf(" %c", &inputOption);
		dict_1 (clnt, inputOption);		
	}
	
	clnt_destroy (clnt);

	exit (0);
}
