/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DICTIONARY_H_RPCGEN
#define _DICTIONARY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct WM {
	char *word;
	char *meaning;
};
typedef struct WM WM;

#define DICTIONARY 0x3a3afeeb
#define DICTIONARY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define newWord 1
extern  char ** newword_1(WM *, CLIENT *);
extern  char ** newword_1_svc(WM *, struct svc_req *);
#define searchWord 2
extern  char ** searchword_1(char **, CLIENT *);
extern  char ** searchword_1_svc(char **, struct svc_req *);
#define deleteWord 3
extern  char ** deleteword_1(char **, CLIENT *);
extern  char ** deleteword_1_svc(char **, struct svc_req *);
extern int dictionary_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define newWord 1
extern  char ** newword_1();
extern  char ** newword_1_svc();
#define searchWord 2
extern  char ** searchword_1();
extern  char ** searchword_1_svc();
#define deleteWord 3
extern  char ** deleteword_1();
extern  char ** deleteword_1_svc();
extern int dictionary_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_WM (XDR *, WM*);

#else /* K&R C */
extern bool_t xdr_WM ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DICTIONARY_H_RPCGEN */
