/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dictionary.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define TABLE_SIZE 1000

/**
 * 
 * Structure of the dictionary that can hold word, its meaning and next dictionary element pointer, if there is collision
 * 
 **/ 
typedef struct Dictionary {
    char* word;
    char* meaning;
    struct Dictionary *next;
} Dictionary;

//Global Hashtable containing list of dictionaries
static Dictionary* dictionary[TABLE_SIZE];

/**
 * 
 * Initialize the hashtable with each element as null
 * 
 **/ 
void init(){
    int i;
    for(i=0; i<TABLE_SIZE; i++){
        dictionary[i] = NULL;
    }
}

/**
 * 
 * Generate hash key for a given word, it will range from 0 to 999
 * 
 **/ 
unsigned int generateHashKey(char* word){
    unsigned int hash = 0;
    for(; *word ; word++){
        hash = *word + hash * 47;
    }
    return hash % TABLE_SIZE;
}

/**
 * 
 * Method to search a given work in the prepopulated hashtable. 
 * 
 **/
Dictionary* lookup(char* word){
    int hashKey = generateHashKey(word);
    //Get the hashed bucket
    Dictionary* dict = dictionary[hashKey];
    //Iterate through each element in the bucket to get matched word
    for(; dict != NULL; dict = dict->next){
        if(strcmp(dict->word, word) == 0){
            // Wow, Got the word with meaning
            return dict;
        }
    }
    return NULL;
}

/**
 * 
 * Method to duplicate the given string
 * 
 **/ 
char* duplicateString(char* input){
    int length = strlen(input) + 1;
    char* output = (char*) malloc(length);
    strcpy(output, input);
    return output;
}

/**
 * 
 * Method to add word with its meaning into global hashtable.
 * When the word with meaning is already available in table then it will return NULL else will return the added word
 * 
 **/ 
char* addToDictionary(char* word, char* meaning){
    Dictionary* dict;
    //Search for word in the dictionary
    if((dict = lookup(word)) == NULL){
        printf("Adding [%s] to dictionary with meaning as [%s]\n", word, meaning);
        int hashKey = generateHashKey(word);
        dict = (Dictionary*) malloc(sizeof(Dictionary));
        dict->word = duplicateString(word);
        dict->meaning = duplicateString(meaning);
        dict->next = dictionary[hashKey];
        dictionary[hashKey] = dict;
    } else {
        printf("Oops Word [%s] found in the dictionary, hence not adding to the dictionary\n", word);
        return NULL;
    }
    return dictionary[generateHashKey(word)]->word;
}

/**
 * 
 * Method to delete a given word from the hashtable.
 * On delete of the word, it will return the word with meaning.
 * When the word is not found, it will return NULL
 * 
 **/ 
 Dictionary* delete(char* word){
     int hashKey = generateHashKey(word);
     Dictionary* curr = dictionary[hashKey];
     Dictionary* prev = NULL;
     for(; curr != NULL; curr = curr->next){
         if(strcmp(curr->word, word) == 0){
             if(prev == NULL){
                dictionary[hashKey] = curr->next;
             } else {
                 prev->next = curr->next;
             }
             printf("Deleting... [%s] meaning [%s]\n", curr->word, curr->meaning);
             return curr; 
         }
         prev = curr;
     }
     printf("Could not found [%s] to delete it\n", word);
     return NULL;
 }
 
/**
 * 
 * Method to print content of the global hashtable
 * 
 **/ 
void printContent(){
    int i;
    printf("---------------------------------Dictionary Contents Start-------------------------------------------------\n");
    for(i = 0; i<TABLE_SIZE; i++){
        if(dictionary[i] != NULL){
            Dictionary *dict = dictionary[i];
            for(; dict != NULL; dict = dict->next){
                printf("%s :: %s\n",dict->word, dict->meaning);
            }    
        }
    }
    printf("-----------------------------------------------------------------------------------------------------------\n");
}


char ** newword_1_svc(WordWithMeaning *wwm, struct svc_req *rqstp)
{
	static char * result;

	printf("Received Word [%s] meaning [%s] \n",wwm->word, wwm->meaning);
	
	char* addedWord = addToDictionary(wwm->word, wwm->meaning);
	if(addedWord != NULL) {
		result = addedWord;
		printf("Added [%s]\n", result );
	}else{
		result = "";
		printf("Word[%s] is available in dictionary\n", wwm->word);
	}
	
	return &result;
}

char ** searchword_1_svc(char **word, struct svc_req *rqstp)
{
	static char * result;
	Dictionary* dict = lookup(*word);
	if(dict != NULL){
		printf("Found [%s] in dictionary\n", dict->word);
		result = dict->meaning;
	} else {
		result = "";
	}
	return &result;
}

char ** deleteword_1_svc(char ** word, struct svc_req *rqstp)
{
	static char * result;
	Dictionary* dict = delete(*word);
	if(dict != NULL){
		printf("Inside delete\n");
		result = dict->meaning;
	}else{
		result = "";
	}	
	return &result;
}
